name: Travis_CI_esmtpm

os:
  - linux
dist: xenial

language: node_js
node_js:
  - "stable"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

git:
  depth: 3
  quiet: true

before_install:
  - npm i -g npm@>=6.14.x

services:
  - mongodb



addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache: npm

notifications:
  email:
    recipients:
      - dmreh@outlook.com
      - m.rehnert@safethishome.com
    on_success: never # default: change
    on_failure: always # default: always
