name: Travis_CI_esmtpm

language: node_js
node_js:
  - 14

on:
  push:
    branches:
      only: [main]
  pull_request:
    branches:
      only: [main]

deploy:
  - app: actionable
    provider: heroku
    skip_cleanup: true
    api_key:
      secure: $HEROKU_API_KEY

notifications:
  email:
    recipients:
      - dmreh@outlook.com
      - m.rehnert@safethishome.com
    on_success: always # default: change
    on_failure: always # default: always
