name: Travis_CI_esmtpm

language: node_js
node_js:
  - 14
os:
  - linux
dist: xenial

git:
  depth: 3
  quiet: true

before_install:
  - npm i -g npm@>=6.14.x

build:
  - run: npm ci
  - run: npm run test

on:
  push:
    branches:
      only: [main]
  pull_request:
    branches:
      only: [main]

deploy:
  - app: actionable
    provider: heroku
    skip_cleanup: true
    api_key:
      secure: $HEROKU_API_KEY

notifications:
  email:
    recipients:
      - dmreh@outlook.com
      - m.rehnert@safethishome.com
    on_success: always # default: change
    on_failure: always # default: always
