name: Travis_CI_esmtpm
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
before_install:
  - npm i -g npm@6.14.x
language: node_js
node_js:
  - lts/*
  - 14
  - 12
 os:
  - linux
dist: xenial
git:
  depth: 3
  quiet: true
jobs:
  build:
    - run: npm ci
    - run: npm run dev
    - run: node server
    - run: npm ci
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - "test.js"
cache: npm

notifications:
  email:
    recipients:
      - dmreh@outlook.com
      - m.rehnert@safethishome.com
    on_success: never # default: change
    on_failure: always # default: always


