name: Travis_CI_esmtpm

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

language: node_js
node_js:
  - 14
  - 12
os:
  - linux
dist: focal

git:
  depth: 3
  quiet: true

before_install:
  - npm i -g npm@>=6.14.x

jobs:
  build:
    - run: npm ci
    - run: npm install
    - run: npm run dev
    - run: npm ci

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - "test.js"

npm cache: true

notifications:
  email:
    recipients:
      - dmreh@outlook.com
      - m.rehnert@safethishome.com
    on_success: never # default: change
    on_failure: always # default: always
